apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dotnet-monorepo-template
  title: Dotnet Monorepo Template
  description: A template for creating a .NET monorepo with multiple services.
  tags:
    - dotnet
    - monorepo
spec:
  owner: builds-processes-squad
  type: template
  parameters:
    - title: Fill in the following steps
      required:
      - domain
      - owner
      properties:
        domain:
          title: Domain
          type: object
          required:
          - domain
          - system
          ui:field: DojoSystemPicker
        owner:
          title: Owner
          type: object
          required:
          - tribe
          - squad
          ui:field: DojoSquadPicker
          ui:options:
            preSelectOwned: true
  
  steps:
    - id: fetch_template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./template
        cookiecutterCompat: false
        values:
          repo_name: ${{ parameters.domain.domain | replace('-domain', '') }}
          repo_owner: 'dojo-engineering-dev'

          owner: ${{ parameters.owner.squad | replace('-squad', '') }}
          domain: ${{ parameters.domain.domain | replace('-domain', '') }}
          system: ${{ parameters.domain.system | replace('-system', '') }}
    
    - id: create-repo
      name: Create Repository
      action: publish:github
      input:
       repoUrl: github.com?owner=dojo-engineering-dev&repo=${{ parameters.domain.domain | replace('-domain', '') }}
       description: "Initial commit for ${{ parameters.domain.domain | replace('-domain', '') }} .NET monorepo with multiple services."
       defaultBranch: main
