name: Build WIP Branch

on:
  push:
    branches:
      - '!main'
      - '!master'
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'task/*'

jobs:
  build:
    uses: dojo-engineering/github-workflows/.github/workflows/dotnet-monorepo-build.yml@main
    with:
      area: ${{ values.domain }}
      solution: ${{ values.domain }}.sln
      disable_conductor: true
      verify_communications_templates: true
      communications_uploader_version: '3.0'
      # uncomment if you want detailed test results in the build output
      # tests_verbosity: 'detailed'
      # test_output_pages_path: './e2e/${{ values.domain }}.IntegrationTest/TestResultsOutput' # probably won't be needed
    secrets: inherit

#  E2E_SIT_Test_Results:
#    if: ${{ success() || failure() }} # run this step even if previous step failed
#    name: E2E Test Report
#    uses: ./.github/workflows/e2e-html-reporting.yaml
#    needs: Build
#    with:
#      area: ${{ values.domain }}
#      solution: ${{ values.domain }}.sln
#    secrets: inherit
