name: Build WIP Branch

on:
  push:
    branches:
      - '!main'
      - '!master'
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'task/*'

jobs:
  build:
    uses: dojo-engineering/github-workflows/.github/workflows/dotnet-monorepo-build.yml@main
    with:
      area: <domain-area>
      solution: Repository.sln
      disable_conductor: true
    secrets: inherit