name: Build WIP Branch

on:
  push:
    branches:
      - '!main'
      - '!master'
      - 'bugfix/*'
      - 'feature/*'
      - 'hotfix/*'
      - 'release/*'
      - 'task/*'

jobs:
  build:
    uses: dojo-engineering/github-workflows/.github/workflows/dotnet-monorepo-build.yml@main
    with:
      area: ${{ values.domain }} # insert domain name in this part of file
      solution: ${{ values.domain }}.sln # possibly change to name of domain -> <Domain>.sln
      disable_conductor: true
    secrets: inherit
